project_name: Rosey CloudCannon Connector Docs
default_og_image: /assets/images/logos/cloudcannon.svg
favicon:
  small_icon: /assets/images/meta/favicon-16x16.png
  large_icon: /assets/images/meta/favicon-32x32.png
  apple_touch_icon: /assets/images/meta/apple-touch-icon.png
  shortcut_icon: /assets/images/meta/favicon.ico