name: Run Tests

on:
  push:
    branches:
      - main
      - tests # TODO: remove this before merge
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install
          cd tests
          npm install 
          npm test